Repository iofoundry/ontology, pull requests merged in 2023-01, with the labels that each got.

#29 Delete GitHub action for hygiene tests
  .github/workflows/hygiene_test_runner.yml
Labels: CD/CI

#30 Initial root readme file for IOF
  README.md
Labels: documentation

#31 Update to versionIRI in accordance to IRI Structure and Format V2.1 spec
  core/commons-to-core-mapping/meta/MappingAnnotationVocabularyToCommons.rdf
  core/meta/AnnotationVocabulary.rdf
  maintenance/Maintenance.rdf
Labels: IRI change

#28 Metadata and config for iof
  MetadataIOF.rdf
  catalog-v001.xml
  core/Metadatacore.rdf
  etc/onto-viewer-web-app/config/application_config.yaml
  etc/onto-viewer-web-app/config/groups_config.yaml
  etc/onto-viewer-web-app/config/label_config.yaml
  etc/onto-viewer-web-app/config/ontology_config.yaml
  etc/onto-viewer-web-app/config/search_config.yaml
  maintenance/Metadatamaintenance.rdf
  supplychain/Metadatasupplychain.rdf
Labels: metadata

#35 Hotfix to Metdatacore ontology
  MetadataIOF.rdf
  catalog-v001.xml
  core/Metadatacore.rdf
Labels: bug, IRI change

#27 Revised Release Notes and Readme Markdown Files
  core/README.md
Labels: documentation

#36 Hotfix to wrong IRIs in Metadata.rdf file
  core/Metadatacore.rdf
  core/commonstocoremapping/meta/MappingAnnotationVocabularyToCommons.rdf
Labels: bug
